//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_t
    {
        public int id_num { get; set; }
        public Nullable<int> invoice_number { get; set; }
        public string customer_name { get; set; }
        public string product_name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> total_Amount { get; set; }
        public string Date { get; set; }
    }
}
